services:
  postgres:
    image: postgres:13.3
    container_name: postgres
    environment:
      POSTGRES_DB: "data"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
    ports:
      - 5432:5432
    volumes:
      - postgres_storage:/data

volumes:
  postgres_storage: {}

# cd ./mikq
# sudo docker compose up -d
# sudo docker compose exec postgres psql -u admin -d data
# sudo docker compose down